version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'react'
        versions: ['18.x']
      - dependency-name: 'react-dom'
        versions: ['18.x']
